"""no Extra

Revision ID: 2316ce882b3c
Revises: 1e4888750a83
Create Date: 2026-06-29 14:55:34.522936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2316ce882b3c'
down_revision = '1e4888750a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
