# Generated by Django 3.2.7 on 2021-09-12 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_of_borrow',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2021, 10, 12, 13, 0, 43, 901763)),
        ),
    ]
