# Generated by Django 3.2.7 on 2021-09-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210914_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='craetor',
            new_name='creator',
        ),
    ]
